language: java
jdk:
- oraclejdk8
script:
- mvn install:install-file -Dfile=uitest-framework/lib/ojdbc6.jar -DgroupId=com.oracle -DartifactId=ojdbc6 -Dversion=11.2.0 -Dpackaging=jar
- mvn install -Dskip_tests=true
